name: deepicedrainpipe
channels:
  - conda-forge
  - nodefaults
dependencies:
  - icepyx=0.6.4
  - jupyter-book=0.13.1
  - jupyterlab=3.5.0
  - jupytext=1.14.0
  - python=3.9
  - pip:
    - git+https://github.com/weiji14/datatree.git@reset-pointer
