name: deepicedrainpipe
channels:
  - conda-forge
  - nodefaults
dependencies:
  - icepyx=0.6.4
  - jupyter-book=0.13.1
  - jupyterlab=3.5.0
  - jupytext=1.14.0
  - pyarrow=9.0.0
  - python=3.9
  - s3fs=2022.11.0
  - xarray-datatree=0.0.11
