# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: DeepIceDrain
author: Wei Ji Leong, Jessica Scheick, Wilson Sauthoff
logo: logo.svg

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false
  # google_analytics_id: G-XXXXXXXXX
  extra_footer: |
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />
    This content is licensed under a
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

parse:
  # https://jupyterbook.org/content/content-blocks.html?highlight=myst%20substitution#define-substitutions-for-your-whole-book
  # https://jupyterbook.org/content/content-blocks.html#using-substitutions-in-links
  myst_substitutions:
    website_url: "https://geo-smart.github.io/use_case_template"
  myst_enable_extensions:
    # Defaults
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    # Extras
    - html_image

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # NOTE: 'cache' to use jupyter-cache, or 'force' to run all
  execute_notebooks: 'off'
  exclude_patterns: ["*rendered*", "*skip*"]
  allow_errors: false
  # Per-cell notebook execution limit (seconds)
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: deepicedrain.tex

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: https://mybinder.org

# Information about where the book exists on the web
repository:
  url: https://github.com/geo-smart/deepicedrainpipe  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

only_build_toc_files: true

# Bibliography
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    bibtex_reference_style: author_year # or label, super, \supercite
    html_show_copyright: false
    # https://jupyterbook.org/en/stable/file-types/jupytext.html
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
